        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 08 23:00:21 2019
        MODULE J4SAVE__genmod
          INTERFACE 
            FUNCTION J4SAVE(IWHICH,IVALUE,ISET)
              INTEGER(KIND=4) :: IWHICH
              INTEGER(KIND=4) :: IVALUE
              LOGICAL(KIND=4) :: ISET
              INTEGER(KIND=4) :: J4SAVE
            END FUNCTION J4SAVE
          END INTERFACE 
        END MODULE J4SAVE__genmod
