        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 08 23:00:21 2019
        MODULE XGETUA__genmod
          INTERFACE 
            SUBROUTINE XGETUA(IUNITA,N)
              INTEGER(KIND=4) :: IUNITA(5)
              INTEGER(KIND=4) :: N
            END SUBROUTINE XGETUA
          END INTERFACE 
        END MODULE XGETUA__genmod
